spring:
    datasource:
        url: @jdbc.mysql.url@
        username: @jdbc.mysql.user@
        password: @jdbc.mysql.pwd@
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 10
        max-idle: 5
        min-idle: 1
        test-while-idle: true
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    enable_lazy_load_no_trans: true

flyway:
    schemas: springbootvalidation